# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '小窗.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setLayoutDirection(Qt.RightToLeft)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.label.setAlignment(Qt.AlignCenter)  # 居中对齐（默认）
        self.label.setScaledContents(True)  # 允许内容自适应缩放


        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "请确认图中产品是不是存在问题，并给出你的答案"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_2.setText(_translate("Dialog", "NG"))
        self.pushButton.setText(_translate("Dialog", "OK"))


class ResizableDialog(QtWidgets.QDialog):
    def __init__(self, parent=None, qimage=None):
        super().__init__(parent)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.qimage = qimage

        # 设置窗口的大小策略
        self.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.setMinimumSize(200, 200)  # 设置最小大小

        # 加载图片
        self.pixmap = QtGui.QPixmap.fromImage(self.qimage)
        if self.pixmap.isNull():
            print("Pixmap is null. Image failed to load.")
            QtWidgets.QMessageBox.warning(self, "错误", "图片加载失败，请检查图片路径或格式。")
            return

        # 初始缩放图片
        self.scale_pixmap()

    def scale_pixmap(self):
        """根据 QLabel 的大小缩放图片"""
        if self.pixmap.isNull():
            return

        # 获取 QLabel 的当前大小
        label_size = self.ui.label.size()

        # 缩放图片以适应 QLabel 的大小
        scaled_pixmap = self.pixmap.scaled(
            label_size,  # 目标尺寸
            Qt.KeepAspectRatio,  # 保持宽高比
            Qt.SmoothTransformation  # 使用平滑缩放
        )
        self.ui.label.setPixmap(scaled_pixmap)

    def resizeEvent(self, event):
        """重写 resizeEvent，在窗口大小变化时调整图片"""
        super().resizeEvent(event)
        self.scale_pixmap()  # 缩放图片以适应新的 QLabel 大小